version: 2
jobs:
  build: 
    working_directory: ~/edx-theme
    docker: 
      - image: circleci/python:2.7
    steps: 
      - checkout
      - run: echo '[edxapp-server]' > ~/inventory
      - run: echo $STAGING_SERVER >> ~/inventory
  deploy: 
    working_directory: ~/edx-theme
    docker: 
      - image: circleci/python:2.7
    steps:
      - run: 
          name: Deploy to staging
          command: deactivate && ~/edx-theme/deploy/deploy_staging.sh
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          # build has to be completed first
          requires:
            - build

          # only run this job on the develop branch
          filters:
            branches:
              only:
                - develop
                - /feature.*/